// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dependency

import (
	"github.com/alexandria-oss/identity-api/internal/common"
	"github.com/alexandria-oss/identity-api/internal/domain"
	"github.com/alexandria-oss/identity-api/internal/infrastructure"
	"github.com/alexandria-oss/identity-api/internal/query"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InjectUserQuery() *query.UserQueryImp {
	kernelStore := common.NewKernelStore()
	userQueryAWSRepository := infrastructure.NewUserQueryAWSRepository(kernelStore)
	userQueryImp := query.NewUserQueryImp(userQueryAWSRepository)
	return userQueryImp
}

// wire.go:

var userQuery = wire.NewSet(common.NewKernelStore, wire.Bind(new(domain.UserQueryRepository), new(*infrastructure.UserQueryAWSRepository)), infrastructure.NewUserQueryAWSRepository, query.NewUserQueryImp)
