alexandria:
  aws:
    cognito:
      user-pool-id: "XXXX"
      user-secret-key: "XXXX"
  persistence:
    cache:
      address:
      - localhost:6379
      database: 0
      network: tcp
      password: ""
      username: ""
  service: identity
  version: "1"
