alexandria:
  service: identity
  version: "1"
  api-version: v1
  aws:
    cognito:
      user-pool-id: ""
      user-secret-key: ""
  persistence:
    cache:
      address:
      - localhost:6379
      database: 0
      network: tcp
      password: ""
      username: ""
  tracing:
    jaeger:
      agent: localhost:6831
      collector: http://localhost:14268/api/traces
      password: ""
      username: ""
  transport:
    http:
      address: localhost:8080
