alexandria:
  service: identity
  version: "1"
  environment: dev
  api-version: v1
  aws:
    cognito:
      user-pool-id: ""
      user-secret-key: ""
  persistence:
    cache:
      address:
      - redis:6379
      database: 0
      network: tcp
      password: ""
      username: ""
  tracing:
    jaeger:
      agent: jaeger:6831
      collector: http://jaeger:14268/api/traces
      password: ""
      username: ""
  transport:
    http:
      address: 0.0.0.0:8080
    grpc:
      address: 0.0.0.0:9090
